### PR TITLE
OpenAI Key in Settings

### LINKED ISSUE #3: settings: manage OpenAI API Keys
**Allow users to set and manage their own OpenAI API keys**

Some features can be enhanced by using LLMs. For example Query Generation for GraphQL APIs. As an oss project, users will need to set their own OpenAI API keys to access these functionalities.

**Current status**
The application loads the open api key from the env variables/`.env` file. If the variable is not defined the app does not launch. 

**Objective** 
- Provide a way for users to input and store their OpenAI API keys in the settings.
- Allow users to update or change their API keys at any point.
- If a user does not provide an API key, the application should continue to function as expected, with the exception that the chat feature should be disabled or hidden.

### PR DESCRIPTION
**Pull request by VictoriaVM**

### CODE REVIEW

File: pkg/settings/manager.go [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+	"reflect"
+	"time"
+
+	bolt "go.etcd.io/bbolt"
+)
+
+// Settings represents user settings.
+type Settings struct {
+    // OpenaiKey is an OpenAI API Key to use with Assistant for GraphQL queries.
+	OpenaiKey string `json:"openai_key"`
```
Comment (positiveblue) [inline pkg/settings/manager.go:15]: It looks like this file isn’t properly formatted according to Go’s standards. 

Go has an ‘official’ formatter called `go fmt` that helps with this. You can configure your editor (WebStorm?) to automatically run `go fmt` on each Go file when you save it.

File: pkg/settings/manager.go [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+	db *bolt.DB
+}
+
+// NewManager creates a new settings manager.
+func NewManager(db *bolt.DB) *Manager {
+	return &Manager{db: db}
+}
+
+// UpdateSettings updates the fields of a Settings instance in the database.
+func (m *Manager) UpdateSettings(ctx context.Context, settings *Settings) error {
```
Comment (positiveblue) [inline pkg/settings/manager.go:31]: I think the code might be a bit overcomplicated given that we’re working with a key-value store like bbolt. 

Instead of using reflection to iterate over the fields and preserve `CreatedAt`, we could simplify this by assuming that the new settings object will have all the necessary fields so we can directly marshal and store it.


There is no need to have a created_at field for settings. Feel free to delete the Field in the struct + simplify this.

File: frontend/src/pages/Settings.tsx [hunk 3]
```diff
@@ -1,22 +1,59 @@
...
+                // Refresh the settings from the database
+                refreshSettings();
+            })
+            .catch((err: any) => {
+                console.error('Error saving credentials:', err);
+                setError('Failed to save credentials');
+            });
+    };
+
+    const dirty = useMemo(() => openaiKey !== settings?.openai_key, [openaiKey, settings])
```
Comment (positiveblue) [inline frontend/src/pages/Settings.tsx]: maybe it's simpler to have a flag "has changed" and whenever the user changes a field (even if it is to set the same value) we allow them to "save".

That should simplify the logic when we add more fields

File: frontend/src/pages/Settings.tsx [hunk 4]
```diff
@@ -1,22 +1,59 @@
...
         Version().then(setVersion);
     }, []);
 
+    useEffect(() => {
+        setOpenaiKey(settings?.openai_key || '');
+    }, [settings]);
+
+    const handleSaveSettings = () => {
+        // Trim the openaiKey only when saving
+        const trimmedKey = openaiKey.trim()
```
Comment (positiveblue) [inline frontend/src/pages/Settings.tsx]:
```
const data = {
             openai_key: openaiKey.trim(),
 };
 ```

File: frontend/src/App.tsx [hunk 5]
```diff
@@ -20,8 +20,16 @@ type CredentialsContextType = {
   refreshCredentials: () => Promise<void>;
 };
 
+// Define the context type
+type SettingsContextType = {
+    settings: any; // Replace 'any' with a more specific type if possible
```
Comment (positiveblue) [inline frontend/src/App.tsx]: can't we use something generated by wails here?

**Review by positiveblue — CHANGES_REQUESTED** [review]
Wow @VictoriaVM nice work. In a couple of days you will be writing better go code than I do!

I left a couple of comments with small simplifications. After that we will have green light for merging 🚦 🎉

File: pkg/settings/manager.go (hunk 2 above)
Comment (VictoriaVM) [reply pkg/settings/manager.go:31]: Do you mean making it as simple as this? 

```
// UpdateSettings updates the fields of a Settings instance in the database.
func (m *Manager) UpdateSettings(ctx context.Context, settings *Settings) error {
	return m.db.Update(func(tx *bolt.Tx) error {
		b, err := tx.CreateBucketIfNotExists([]byte("settings"))
		if err != nil {
			return fmt.Errorf("create bucket: %w", err)
		}

		settings.UpdatedAt = time.Now().UTC()
        
       // Marshal the settings back to JSON
       value, err = json.Marshal(settings)
       if err != nil {
        return fmt.Errorf("encode settings: %w", err)
       }

		// Put the settings back into the bucket
		return b.Put(key, value)
	})
}
```

Comment (positiveblue) [reply pkg/settings/manager.go:31]: Exactly

**Review by positiveblue — APPROVED** [review]
🫡
